#!/bin/sh
alias config='/usr/bin/git --git-dir=$HOME/dotfiles/ --work-tree=$HOME'

alias ls="ls --color=auto"
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias grep='grep --color=auto'

alias mkdir='mkdir -pv'

alias mv='mv -i'
alias rm='rm -i'
alias cp='cp -i'
alias ln='ln -i'

alias ..='cd ..'

alias vim='vim -c "let g:tty='\''$(tty)'\''"'

alias diff='icdiff'
