" VIMRC
" set shell to zsh
:set shell=/usr/bin/zsh

" minimal settings
set nocompatible
set backspace=indent,eol,start
set hidden
set noswapfile


let $RTP=split(&runtimepath, ',')[0]
let $RC="$HOME/.vim/vimrc"

command! W execute 'w !sudo tee % > /dev/null' <bar> edit!

" Search down into subfolders
" Provides tab-completion for all file-related tasks
set path+=**

" default indentation
set shiftwidth=4
set softtabstop=4
set expandtab
set autoindent


" UI
set showmode

set showcmd
set cmdheight=1

set laststatus=2

set wildmenu
set ruler

set showmatch


" FILE BROWSING
let g:netrw_banner=0        " disable annoying banner
let g:netrw_browse_split=4  " open in prior window
let g:netrw_altv=1          " open splits to the right
let g:netrw_liststyle=3     " tree view
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\b'


" editing goodies
set cursorline
set listchars=tab:>-,nbsp:_,trail:_,eol:§,extends:>,precedes:<
set showbreak=\\

set ignorecase
set smartcase

set hlsearch
set incsearch
set number relativenumber

set colorcolumn=80,120


" TAG JUMPING
" Create the `tags` file
command! MakeTags !ctags -R .


" Syntax Highlighting
" Codecompletion
syntax enable
:filetype plugin indent on
    if has("autocmd") && exists("+omnifunc")
        autocmd Filetype *
            \   if &omnifunc == "" |
            \       setlocal omnifunc=syntaxcomplete#Complete |
            \   endif
    endif

:set completeopt=longest,menuone

:inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

inoremap <expr> <C-n> pumvisible() ? '<C-n>' :
  \ '<C-n><C-r>=pumvisible() ? "\<lt>Down>" : ""<CR>'
inoremap <expr> <M-,> pumvisible() ? '<C-n>' :
  \ '<C-x><C-o><C-n><C-p><C-r>=pumvisible() ? "\<lt>Down>" : ""<CR>'

" open omni completion menu closing previous if open and opening new menu without changing the text
inoremap <expr> <C-@> (pumvisible() ? (col('.') > 1 ? '<Esc>i<Right>' : '<Esc>i') : '') .
            \ '<C-x><C-o><C-r>=pumvisible() ? "\<lt>C-n>\<lt>C-p>\<lt>Down>" : ""<CR>'
" open user completion menu closing previous if open and opening new menu without changing the text
inoremap <expr> <S-@> (pumvisible() ? (col('.') > 1 ? '<Esc>i<Right>' : '<Esc>i') : '') .
            \ '<C-x><C-u><C-r>=pumvisible() ? "\<lt>C-n>\<lt>C-p>\<lt>Down>" : ""<CR>'


" SNIPPETS
nnoremap \html :-1read $HOME/.vim/templates/skeleton.html<CR>3jwf>a


" colortheme
set background=dark
colorscheme solarized
call togglebg#map("<F5>")

highlight SpecialKey ctermfg=1


" Statusline
function! GitBranch()
  return trim(system("git -C " . expand("%:h") . " branch --show-current 2>/dev/null"))
endfunction

autocmd BufWinEnter * let b:git_branch = GitBranch()

set statusline=
set statusline+=%{b:git_branch}
set statusline+=\ %F\ %M\ %Y\ %{&fileencoding?&fileencoding:&encoding}\[%{&fileformat}\]%r
set statusline+=%=%l\:%c\ %p%%
set statusline+=%=ascii:\ %b\ hex:\ 0x%B


" Map key to toggle opt
function! MapToggle(key, opt)
  let cmd = ':set '.a:opt.'! \| set '.a:opt."?\<CR>"
  exec 'nnoremap '.a:key.' '.cmd
  exec 'inoremap '.a:key." \<C-O>".cmd
endfunction
command -nargs=+ MapToggle call MapToggle(<f-args>)

MapToggle <F6> list
MapToggle <F7> hlsearch
MapToggle <F8> incsearch
MapToggle <F9> relativenumber
